In [1]:
import tensorflow as tf
import numpy as np

In [2]:
#loadtxt()는 파일 읽어오게하는 함수 
# delimiter 구분자
# dtype 타입을 알려줘야한다.
xy = np.loadtxt('../data/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1] 
y_data = xy[:, [-1]] 

In [3]:
print(x_data,'\nx_data shape:', x_data.shape)
print(y_data,'\ny_data shape:', y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [4]:
tf.model = tf.keras.Sequential()

# activation 활성화함수는 제일 마지막에만 붙여한다.
# 제일앞에 대문자면 참조자료형
# 매개변수는 스스로 new해주고있다는 의미이다.
tf.model.add(tf.keras.layers.Dense(input_dim=3, units=1, activation='linear'))


In [5]:
tf.model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [6]:
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(learning_rate=1e-5))

In [7]:
tf.model.fit(x_data, y_data, epochs=3500)

Epoch 1/3500
1/1 [==============================] - 0s 345ms/step - loss: 9197.9883
Epoch 2/3500
1/1 [==============================] - 0s 9ms/step - loss: 3406.3518
Epoch 3/3500
1/1 [==============================] - 0s 15ms/step - loss: 1265.0229
Epoch 4/3500
1/1 [==============================] - 0s 17ms/step - loss: 473.3132
Epoch 5/3500
1/1 [==============================] - 0s 18ms/step - loss: 180.5945
Epoch 6/3500
1/1 [==============================] - 0s 11ms/step - loss: 72.3668
Epoch 7/3500
1/1 [==============================] - 0s 5ms/step - loss: 32.3505
Epoch 8/3500
1/1 [==============================] - 0s 7ms/step - loss: 17.5539
Epoch 9/3500
1/1 [==============================] - 0s 13ms/step - loss: 12.0816
Epoch 10/3500
1/1 [==============================] - 0s 6ms/step - loss: 10.0568
Epoch 11/3500
1/1 [==============================] - 0s 8ms/step - loss: 9.3067
Epoch 12/3500
1/1 [==============================] - 0s 13ms/step - loss: 9.0279
Epoch 13/3500
1/1 [====

1/1 [==============================] - 0s 9ms/step - loss: 8.6558
Epoch 104/3500
1/1 [==============================] - 0s 5ms/step - loss: 8.6536
Epoch 105/3500
1/1 [==============================] - 0s 4ms/step - loss: 8.6514
Epoch 106/3500
1/1 [==============================] - 0s 7ms/step - loss: 8.6491
Epoch 107/3500
1/1 [==============================] - 0s 5ms/step - loss: 8.6469
Epoch 108/3500
1/1 [==============================] - 0s 5ms/step - loss: 8.6447
Epoch 109/3500
1/1 [==============================] - 0s 4ms/step - loss: 8.6425
Epoch 110/3500
1/1 [==============================] - 0s 5ms/step - loss: 8.6403
Epoch 111/3500
1/1 [==============================] - 0s 5ms/step - loss: 8.6381
Epoch 112/3500
1/1 [==============================] - 0s 5ms/step - loss: 8.6359
Epoch 113/3500
1/1 [==============================] - 0s 9ms/step - loss: 8.6337
Epoch 114/3500
1/1 [==============================] - 0s 7ms/step - loss: 8.6315
Epoch 115/3500
1/1 [=======================

1/1 [==============================] - 0s 5ms/step - loss: 8.2455
Epoch 306/3500
1/1 [==============================] - 0s 4ms/step - loss: 8.2437
Epoch 307/3500
1/1 [==============================] - 0s 4ms/step - loss: 8.2418
Epoch 308/3500
1/1 [==============================] - 0s 4ms/step - loss: 8.2400
Epoch 309/3500
1/1 [==============================] - 0s 5ms/step - loss: 8.2381
Epoch 310/3500
1/1 [==============================] - 0s 5ms/step - loss: 8.2363
Epoch 311/3500
1/1 [==============================] - 0s 7ms/step - loss: 8.2344
Epoch 312/3500
1/1 [==============================] - 0s 10ms/step - loss: 8.2326
Epoch 313/3500
1/1 [==============================] - 0s 5ms/step - loss: 8.2307
Epoch 314/3500
1/1 [==============================] - 0s 4ms/step - loss: 8.2289
Epoch 315/3500
1/1 [==============================] - 0s 4ms/step - loss: 8.2270
Epoch 316/3500
1/1 [==============================] - 0s 4ms/step - loss: 8.2252
Epoch 317/3500
1/1 [======================

1/1 [==============================] - 0s 6ms/step - loss: 7.9018
Epoch 508/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.9002
Epoch 509/3500
1/1 [==============================] - 0s 8ms/step - loss: 7.8987
Epoch 510/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.8971
Epoch 511/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.8956
Epoch 512/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.8940
Epoch 513/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.8925
Epoch 514/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.8909
Epoch 515/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.8894
Epoch 516/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.8878
Epoch 517/3500
1/1 [==============================] - 0s 3ms/step - loss: 7.8863
Epoch 518/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.8847
Epoch 519/3500
1/1 [=======================

1/1 [==============================] - 0s 5ms/step - loss: 7.6137
Epoch 710/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.6124
Epoch 711/3500
1/1 [==============================] - 0s 8ms/step - loss: 7.6111
Epoch 712/3500
1/1 [==============================] - 0s 6ms/step - loss: 7.6098
Epoch 713/3500
1/1 [==============================] - 0s 5ms/step - loss: 7.6085
Epoch 714/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.6072
Epoch 715/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.6059
Epoch 716/3500
1/1 [==============================] - 0s 3ms/step - loss: 7.6046
Epoch 717/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.6033
Epoch 718/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.6020
Epoch 719/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.6007
Epoch 720/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.5994
Epoch 721/3500
1/1 [=======================

1/1 [==============================] - 0s 5ms/step - loss: 7.3722
Epoch 912/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.3711
Epoch 913/3500
1/1 [==============================] - 0s 3ms/step - loss: 7.3700
Epoch 914/3500
1/1 [==============================] - 0s 5ms/step - loss: 7.3689
Epoch 915/3500
1/1 [==============================] - 0s 5ms/step - loss: 7.3678
Epoch 916/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.3667
Epoch 917/3500
1/1 [==============================] - 0s 5ms/step - loss: 7.3656
Epoch 918/3500
1/1 [==============================] - 0s 5ms/step - loss: 7.3646
Epoch 919/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.3635
Epoch 920/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.3624
Epoch 921/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.3613
Epoch 922/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.3602
Epoch 923/3500
1/1 [=======================

1/1 [==============================] - 0s 6ms/step - loss: 7.2665
Epoch 1013/3500
1/1 [==============================] - 0s 6ms/step - loss: 7.2655
Epoch 1014/3500
1/1 [==============================] - 0s 6ms/step - loss: 7.2645
Epoch 1015/3500
1/1 [==============================] - 0s 6ms/step - loss: 7.2635
Epoch 1016/3500
1/1 [==============================] - 0s 3ms/step - loss: 7.2625
Epoch 1017/3500
1/1 [==============================] - 0s 5ms/step - loss: 7.2615
Epoch 1018/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.2605
Epoch 1019/3500
1/1 [==============================] - 0s 5ms/step - loss: 7.2595
Epoch 1020/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.2585
Epoch 1021/3500
1/1 [==============================] - 0s 7ms/step - loss: 7.2575
Epoch 1022/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.2565
Epoch 1023/3500
1/1 [==============================] - 0s 6ms/step - loss: 7.2555
Epoch 1024/3500
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 7.1706
Epoch 1113/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.1697
Epoch 1114/3500
1/1 [==============================] - 0s 5ms/step - loss: 7.1688
Epoch 1115/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.1679
Epoch 1116/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.1669
Epoch 1117/3500
1/1 [==============================] - 0s 3ms/step - loss: 7.1660
Epoch 1118/3500
1/1 [==============================] - 0s 5ms/step - loss: 7.1651
Epoch 1119/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.1642
Epoch 1120/3500
1/1 [==============================] - 0s 6ms/step - loss: 7.1633
Epoch 1121/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.1624
Epoch 1122/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.1615
Epoch 1123/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.1606
Epoch 1124/3500
1/1 [===========

1/1 [==============================] - 0s 5ms/step - loss: 7.0827
Epoch 1213/3500
1/1 [==============================] - 0s 3ms/step - loss: 7.0819
Epoch 1214/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.0810
Epoch 1215/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.0802
Epoch 1216/3500
1/1 [==============================] - 0s 5ms/step - loss: 7.0794
Epoch 1217/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.0785
Epoch 1218/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.0777
Epoch 1219/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.0769
Epoch 1220/3500
1/1 [==============================] - 0s 5ms/step - loss: 7.0760
Epoch 1221/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.0752
Epoch 1222/3500
1/1 [==============================] - 0s 5ms/step - loss: 7.0743
Epoch 1223/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.0735
Epoch 1224/3500
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 7.0022
Epoch 1313/3500
1/1 [==============================] - 0s 5ms/step - loss: 7.0014
Epoch 1314/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.0006
Epoch 1315/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.9998
Epoch 1316/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.9991
Epoch 1317/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.9983
Epoch 1318/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.9975
Epoch 1319/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.9968
Epoch 1320/3500
1/1 [==============================] - 0s 3ms/step - loss: 6.9960
Epoch 1321/3500
1/1 [==============================] - 0s 3ms/step - loss: 6.9953
Epoch 1322/3500
1/1 [==============================] - 0s 8ms/step - loss: 6.9945
Epoch 1323/3500
1/1 [==============================] - 0s 9ms/step - loss: 6.9937
Epoch 1324/3500
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 6.9283
Epoch 1413/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.9276
Epoch 1414/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.9269
Epoch 1415/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.9262
Epoch 1416/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.9255
Epoch 1417/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.9248
Epoch 1418/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.9241
Epoch 1419/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.9234
Epoch 1420/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.9227
Epoch 1421/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.9220
Epoch 1422/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.9213
Epoch 1423/3500
1/1 [==============================] - 0s 14ms/step - loss: 6.9206
Epoch 1424/3500
1/1 [==========

1/1 [==============================] - 0s 4ms/step - loss: 6.8606
Epoch 1513/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.8599
Epoch 1514/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.8593
Epoch 1515/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.8586
Epoch 1516/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.8580
Epoch 1517/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.8573
Epoch 1518/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.8567
Epoch 1519/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.8561
Epoch 1520/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.8554
Epoch 1521/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.8548
Epoch 1522/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.8541
Epoch 1523/3500
1/1 [==============================] - 0s 7ms/step - loss: 6.8535
Epoch 1524/3500
1/1 [===========

1/1 [==============================] - 0s 5ms/step - loss: 6.7985
Epoch 1613/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7979
Epoch 1614/3500
1/1 [==============================] - 0s 3ms/step - loss: 6.7973
Epoch 1615/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7967
Epoch 1616/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.7961
Epoch 1617/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7955
Epoch 1618/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7949
Epoch 1619/3500
1/1 [==============================] - 0s 3ms/step - loss: 6.7944
Epoch 1620/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7938
Epoch 1621/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7932
Epoch 1622/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7926
Epoch 1623/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7920
Epoch 1624/3500
1/1 [===========

1/1 [==============================] - 0s 5ms/step - loss: 6.7416
Epoch 1713/3500
1/1 [==============================] - 0s 10ms/step - loss: 6.7410
Epoch 1714/3500
1/1 [==============================] - 0s 7ms/step - loss: 6.7405
Epoch 1715/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7399
Epoch 1716/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7394
Epoch 1717/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7388
Epoch 1718/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7383
Epoch 1719/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7378
Epoch 1720/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7372
Epoch 1721/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.7367
Epoch 1722/3500
1/1 [==============================] - 0s 3ms/step - loss: 6.7361
Epoch 1723/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.7356
Epoch 1724/3500
1/1 [==========

1/1 [==============================] - 0s 10ms/step - loss: 6.6894
Epoch 1813/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.6889
Epoch 1814/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.6884
Epoch 1815/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.6879
Epoch 1816/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.6874
Epoch 1817/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.6869
Epoch 1818/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.6864
Epoch 1819/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.6859
Epoch 1820/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.6854
Epoch 1821/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.6849
Epoch 1822/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.6844
Epoch 1823/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.6839
Epoch 1824/3500
1/1 [==========

1/1 [==============================] - 0s 4ms/step - loss: 6.6415
Epoch 1913/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.6410
Epoch 1914/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.6406
Epoch 1915/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.6401
Epoch 1916/3500
1/1 [==============================] - 0s 3ms/step - loss: 6.6397
Epoch 1917/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.6392
Epoch 1918/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.6387
Epoch 1919/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.6383
Epoch 1920/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.6378
Epoch 1921/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.6374
Epoch 1922/3500
1/1 [==============================] - 0s 8ms/step - loss: 6.6369
Epoch 1923/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.6365
Epoch 1924/3500
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 6.5976
Epoch 2013/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.5971
Epoch 2014/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.5967
Epoch 2015/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.5963
Epoch 2016/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.5959
Epoch 2017/3500
1/1 [==============================] - 0s 3ms/step - loss: 6.5955
Epoch 2018/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.5951
Epoch 2019/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.5946
Epoch 2020/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.5942
Epoch 2021/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.5938
Epoch 2022/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.5934
Epoch 2023/3500
1/1 [==============================] - 0s 8ms/step - loss: 6.5930
Epoch 2024/3500
1/1 [===========

1/1 [==============================] - 0s 6ms/step - loss: 6.5573
Epoch 2113/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.5569
Epoch 2114/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.5565
Epoch 2115/3500
1/1 [==============================] - 0s 8ms/step - loss: 6.5561
Epoch 2116/3500
1/1 [==============================] - 0s 7ms/step - loss: 6.5557
Epoch 2117/3500
1/1 [==============================] - 0s 7ms/step - loss: 6.5553
Epoch 2118/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.5550
Epoch 2119/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.5546
Epoch 2120/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.5542
Epoch 2121/3500
1/1 [==============================] - 0s 3ms/step - loss: 6.5538
Epoch 2122/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.5534
Epoch 2123/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.5530
Epoch 2124/3500
1/1 [===========

Epoch 2212/3500
1/1 [==============================] - 0s 7ms/step - loss: 6.5203
Epoch 2213/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.5200
Epoch 2214/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.5196
Epoch 2215/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.5193
Epoch 2216/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.5189
Epoch 2217/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.5186
Epoch 2218/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.5182
Epoch 2219/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.5178
Epoch 2220/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.5175
Epoch 2221/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.5171
Epoch 2222/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.5168
Epoch 2223/3500
1/1 [==============================] - 0s 7ms/step - loss: 6.5164
Epoch 2224/3500


1/1 [==============================] - 0s 21ms/step - loss: 6.4556
Epoch 2412/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.4553
Epoch 2413/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.4550
Epoch 2414/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.4547
Epoch 2415/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.4544
Epoch 2416/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.4541
Epoch 2417/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.4538
Epoch 2418/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.4535
Epoch 2419/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.4532
Epoch 2420/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.4529
Epoch 2421/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.4526
Epoch 2422/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.4523
Epoch 2423/3500
1/1 [==========

Epoch 2511/3500
1/1 [==============================] - 0s 8ms/step - loss: 6.4270
Epoch 2512/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.4267
Epoch 2513/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.4265
Epoch 2514/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.4262
Epoch 2515/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.4259
Epoch 2516/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.4256
Epoch 2517/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.4254
Epoch 2518/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.4251
Epoch 2519/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.4248
Epoch 2520/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.4246
Epoch 2521/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.4243
Epoch 2522/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.4240
Epoch 2523/3500


1/1 [==============================] - 0s 4ms/step - loss: 6.3769
Epoch 2711/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.3767
Epoch 2712/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.3765
Epoch 2713/3500
1/1 [==============================] - 0s 22ms/step - loss: 6.3762
Epoch 2714/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3760
Epoch 2715/3500
1/1 [==============================] - 0s 3ms/step - loss: 6.3758
Epoch 2716/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3756
Epoch 2717/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3753
Epoch 2718/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3751
Epoch 2719/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3749
Epoch 2720/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3746
Epoch 2721/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3744
Epoch 2722/3500
1/1 [==========

Epoch 2810/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.3548
Epoch 2811/3500
1/1 [==============================] - 0s 13ms/step - loss: 6.3546
Epoch 2812/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3544
Epoch 2813/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.3542
Epoch 2814/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.3539
Epoch 2815/3500
1/1 [==============================] - 0s 9ms/step - loss: 6.3538
Epoch 2816/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.3536
Epoch 2817/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.3533
Epoch 2818/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.3531
Epoch 2819/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.3529
Epoch 2820/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3527
Epoch 2821/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3525
Epoch 2822/3500

1/1 [==============================] - 0s 20ms/step - loss: 6.3160
Epoch 3010/3500
1/1 [==============================] - 0s 7ms/step - loss: 6.3159
Epoch 3011/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3157
Epoch 3012/3500
1/1 [==============================] - 0s 7ms/step - loss: 6.3155
Epoch 3013/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3153
Epoch 3014/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3151
Epoch 3015/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.3150
Epoch 3016/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3148
Epoch 3017/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.3146
Epoch 3018/3500
1/1 [==============================] - 0s 22ms/step - loss: 6.3144
Epoch 3019/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.3143
Epoch 3020/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.3141
Epoch 3021/3500
1/1 [=========

1/1 [==============================] - 0s 4ms/step - loss: 6.2989
Epoch 3110/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.2987
Epoch 3111/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.2986
Epoch 3112/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2984
Epoch 3113/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.2982
Epoch 3114/3500
1/1 [==============================] - 0s 18ms/step - loss: 6.2981
Epoch 3115/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.2979
Epoch 3116/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.2977
Epoch 3117/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2976
Epoch 3118/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.2974
Epoch 3119/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.2973
Epoch 3120/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2971
Epoch 3121/3500
1/1 [==========

1/1 [==============================] - 0s 24ms/step - loss: 6.2831
Epoch 3210/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2830
Epoch 3211/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.2828
Epoch 3212/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.2827
Epoch 3213/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.2825
Epoch 3214/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.2824
Epoch 3215/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2822
Epoch 3216/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2821
Epoch 3217/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2819
Epoch 3218/3500
1/1 [==============================] - 0s 29ms/step - loss: 6.2818
Epoch 3219/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2816
Epoch 3220/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2815
Epoch 3221/3500
1/1 [=========

Epoch 3309/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.2687
Epoch 3310/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2685
Epoch 3311/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2684
Epoch 3312/3500
1/1 [==============================] - 0s 22ms/step - loss: 6.2683
Epoch 3313/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.2681
Epoch 3314/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2680
Epoch 3315/3500
1/1 [==============================] - 0s 6ms/step - loss: 6.2679
Epoch 3316/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2677
Epoch 3317/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.2676
Epoch 3318/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2674
Epoch 3319/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.2673
Epoch 3320/3500
1/1 [==============================] - 0s 5ms/step - loss: 6.2672
Epoch 3321/3500

In [11]:
print(tf.model.predict([[100., 70., 98.]]))

1/1 [==============================] - 0s 85ms/step
[[181.19893]]
